"""pdf_chunks_eliminate_fk

Revision ID: 8aae2fe7d94f
Revises: 
Create Date: 2025-07-01 15:38:40.771621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aae2fe7d94f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('temp_chunks_chunk_id_fkey'), 'temp_chunks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('temp_chunks_chunk_id_fkey'), 'temp_chunks', 'pdf_chunks', ['chunk_id'], ['chunk_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
