/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp-verification` | `/otp-verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/purchase-premium` | `/purchase-premium`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(drawer)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(drawer)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(drawer)'}/books` | `/books`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(main)'}${'/(drawer)'}/books/[id]` | `/books/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/otp-verification` | `/otp-verification`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/purchase-premium` | `/purchase-premium`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}${'/(drawer)'}/about` | `/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}${'/(drawer)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}${'/(drawer)'}/books` | `/books`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(main)'}${'/(drawer)'}/books/[id]` | `/books/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgot-password${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/otp-verification${`?${string}` | `#${string}` | ''}` | `/otp-verification${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/purchase-premium${`?${string}` | `#${string}` | ''}` | `/purchase-premium${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${'/(drawer)'}/about${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${'/(drawer)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${'/(drawer)'}/books${`?${string}` | `#${string}` | ''}` | `/books${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp-verification` | `/otp-verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/purchase-premium` | `/purchase-premium`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(drawer)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(drawer)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(drawer)'}/books` | `/books`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(main)'}${'/(drawer)'}/books/${Router.SingleRoutePart<T>}` | `/books/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(main)'}${'/(drawer)'}/books/[id]` | `/books/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
